version: "3.9"

services:
  backend:
    container_name: api
    build: backend
    ports:
      - 8080:8080
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=ng
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ng_cash
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ng -d ng_cash"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  frontend:
    build: frontend
    ports:
      - 3000:3000
